{
  imports = [
    ./adguardhome.nix
    ./caddy.nix
    ./deeptutor.nix
    ./express-postmark.nix
    ./gameservers.nix
    ./jellyfin.nix
    ./kavita.nix
    ./linkding.nix
    ./pgadmin.nix
    ./pinchflat.nix
    ./postgres.nix
    ./radicale.nix
    ./syncthing.nix
    ./teamspeak.nix
    ./uptime-kuma.nix
    ./vault.nix
    ./vikunja.nix
  ];
}
